### ISSUE TITLE
Nodemon restart on routes.coffee changes

### ISSUE THREAD

**Issue by adelriosantiago** [Jmlevick/mean-boilerplate#1]
Ok, this question might be a bit stupid but I'm fairly new to Coffee.

The file *routes.coffee* does not compile to any .js file is that correct? I suppose this might be some real-time compiling of the *coffee-script* package. Otherwise where is the .js compiled file?

Also I would like to know why *nodemon* does not restarts automatically when this coffee file is changed. How can I do so?

**Comment by Jmlevick** [comment]
Oh god, I just saw this I'm very very sorry... If it's of any help, no the **routes.coffee** doesn't compile into JS at any time, neither the other .coffee files in the project, so they're not being watched by nodemon because of this. I haven't looked into it, but maybe there's a way for nodemon to "listen" into coffee changes or maybe a watcher could be implemented via Gulp and/or BrowserSync... Anyways, just released v5.0.0 of this project and now you can choose whether you want to use JS or Coffee as your main language:

https://github.com/Jmlevick/mean-boilerplate/blob/master/CHANGELOG.md

On the JS branch, nodemon listens for changes on almost every file in the project ;)

**Comment by nanotime** [comment]
Theoretically it compile coffee but never creates a .js file to use, this is because the project are using the registry of coffee-script:

```javascript
require('coffee-script');
require('coffee-script/register');
```

In that case, Nodemon is watching for changes on `server.js` becasue there is where the compilations happens.

Cheers. :beers:

**Comment by Jmlevick** [comment]
That's a more accurate answer, indeed ".coffee" files "compile on the fly" so the server can read .coffee without any issues. That's why you don't have any .js files for routes or models/controllers (when running a project based off the master branch of the mean boilerplate) and because of that, nodemon isn't able to "watch" for changes on those files by default.

**Comment by nanotime** [comment]
Exactly, if you want to make a change be valid, you need to save the `server.js`, simple :smile:

**Comment by adelriosantiago** [comment]
Thanks both for clarifying that!

Cheers :coffee:

**Comment by Jmlevick** [comment]
I'll close this as solved, then. The easiest way to make nodemon reflect changes on ".coffee" files is indeed re-saving the **server.js ** file as @nanotime commented, it doesn't makes nodemon "watch" for changes in ".coffee" files but it restarts the server reflecting the changes in the app, easy enough ;)
